/*
 * Juke It Out
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 0.1
 * Contact: alex@alexmeuer.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type UserInfo struct {

	Id string `json:"id,omitempty"`

	DisplayName string `json:"displayName,omitempty"`
}
