package room

import "context"

type CreateUseCase struct {
	Writer Writer
}

func (uc *CreateUseCase) Execute(ctx context.Context, name string) (Room, error) {
	room, err := uc.Writer.Write(ctx, Room{
		// ID omitted because it is generated by the Writer (or we expect it to be generated by the Writer).
		Name: name,
	})
	if err != nil {
		return room, err
	}

	return room, nil
}
