package user

import "context"

type CreateUseCase struct {
	Writer Writer
}

// TODO: store tokens
func (uc *CreateUseCase) Execute(ctx context.Context, displayName string) (Public, error) {
	user, err := uc.Writer.Write(ctx, Public{
		// ID omitted because it is generated by the Writer (or we expect it to be generated by the Writer).
		DisplayName: displayName,
	})
	if err != nil {
		return user, err
	}

	return user, nil
}
